/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AAlwaysConstruct extends PAlwaysConstruct
{
    private TKAlways _kAlways_;
    private PStatement _statement_;

    public AAlwaysConstruct()
    {
        // Constructor
    }

    public AAlwaysConstruct(
        @SuppressWarnings("hiding") TKAlways _kAlways_,
        @SuppressWarnings("hiding") PStatement _statement_)
    {
        // Constructor
        setKAlways(_kAlways_);

        setStatement(_statement_);

    }

    @Override
    public Object clone()
    {
        return new AAlwaysConstruct(
            cloneNode(this._kAlways_),
            cloneNode(this._statement_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAlwaysConstruct(this);
    }

    public TKAlways getKAlways()
    {
        return this._kAlways_;
    }

    public void setKAlways(TKAlways node)
    {
        if(this._kAlways_ != null)
        {
            this._kAlways_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kAlways_ = node;
    }

    public PStatement getStatement()
    {
        return this._statement_;
    }

    public void setStatement(PStatement node)
    {
        if(this._statement_ != null)
        {
            this._statement_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statement_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kAlways_)
            + toString(this._statement_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kAlways_ == child)
        {
            this._kAlways_ = null;
            return;
        }

        if(this._statement_ == child)
        {
            this._statement_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kAlways_ == oldChild)
        {
            setKAlways((TKAlways) newChild);
            return;
        }

        if(this._statement_ == oldChild)
        {
            setStatement((PStatement) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
