/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AIntegerDeclaration extends PIntegerDeclaration
{
    private TKInteger _kInteger_;
    private PListOfVariableIdentifiers _listOfVariableIdentifiers_;
    private TTSemicolon _tSemicolon_;

    public AIntegerDeclaration()
    {
        // Constructor
    }

    public AIntegerDeclaration(
        @SuppressWarnings("hiding") TKInteger _kInteger_,
        @SuppressWarnings("hiding") PListOfVariableIdentifiers _listOfVariableIdentifiers_,
        @SuppressWarnings("hiding") TTSemicolon _tSemicolon_)
    {
        // Constructor
        setKInteger(_kInteger_);

        setListOfVariableIdentifiers(_listOfVariableIdentifiers_);

        setTSemicolon(_tSemicolon_);

    }

    @Override
    public Object clone()
    {
        return new AIntegerDeclaration(
            cloneNode(this._kInteger_),
            cloneNode(this._listOfVariableIdentifiers_),
            cloneNode(this._tSemicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntegerDeclaration(this);
    }

    public TKInteger getKInteger()
    {
        return this._kInteger_;
    }

    public void setKInteger(TKInteger node)
    {
        if(this._kInteger_ != null)
        {
            this._kInteger_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kInteger_ = node;
    }

    public PListOfVariableIdentifiers getListOfVariableIdentifiers()
    {
        return this._listOfVariableIdentifiers_;
    }

    public void setListOfVariableIdentifiers(PListOfVariableIdentifiers node)
    {
        if(this._listOfVariableIdentifiers_ != null)
        {
            this._listOfVariableIdentifiers_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listOfVariableIdentifiers_ = node;
    }

    public TTSemicolon getTSemicolon()
    {
        return this._tSemicolon_;
    }

    public void setTSemicolon(TTSemicolon node)
    {
        if(this._tSemicolon_ != null)
        {
            this._tSemicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tSemicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kInteger_)
            + toString(this._listOfVariableIdentifiers_)
            + toString(this._tSemicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kInteger_ == child)
        {
            this._kInteger_ = null;
            return;
        }

        if(this._listOfVariableIdentifiers_ == child)
        {
            this._listOfVariableIdentifiers_ = null;
            return;
        }

        if(this._tSemicolon_ == child)
        {
            this._tSemicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kInteger_ == oldChild)
        {
            setKInteger((TKInteger) newChild);
            return;
        }

        if(this._listOfVariableIdentifiers_ == oldChild)
        {
            setListOfVariableIdentifiers((PListOfVariableIdentifiers) newChild);
            return;
        }

        if(this._tSemicolon_ == oldChild)
        {
            setTSemicolon((TTSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
