/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AMacroModuleKeyword extends PModuleKeyword
{
    private TKMacromodule _kMacromodule_;

    public AMacroModuleKeyword()
    {
        // Constructor
    }

    public AMacroModuleKeyword(
        @SuppressWarnings("hiding") TKMacromodule _kMacromodule_)
    {
        // Constructor
        setKMacromodule(_kMacromodule_);

    }

    @Override
    public Object clone()
    {
        return new AMacroModuleKeyword(
            cloneNode(this._kMacromodule_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMacroModuleKeyword(this);
    }

    public TKMacromodule getKMacromodule()
    {
        return this._kMacromodule_;
    }

    public void setKMacromodule(TKMacromodule node)
    {
        if(this._kMacromodule_ != null)
        {
            this._kMacromodule_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kMacromodule_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kMacromodule_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kMacromodule_ == child)
        {
            this._kMacromodule_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kMacromodule_ == oldChild)
        {
            setKMacromodule((TKMacromodule) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
