/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AMconcatPrimary extends PPrimary
{
    private PMultipleConcatenation _multipleConcatenation_;

    public AMconcatPrimary()
    {
        // Constructor
    }

    public AMconcatPrimary(
        @SuppressWarnings("hiding") PMultipleConcatenation _multipleConcatenation_)
    {
        // Constructor
        setMultipleConcatenation(_multipleConcatenation_);

    }

    @Override
    public Object clone()
    {
        return new AMconcatPrimary(
            cloneNode(this._multipleConcatenation_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMconcatPrimary(this);
    }

    public PMultipleConcatenation getMultipleConcatenation()
    {
        return this._multipleConcatenation_;
    }

    public void setMultipleConcatenation(PMultipleConcatenation node)
    {
        if(this._multipleConcatenation_ != null)
        {
            this._multipleConcatenation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multipleConcatenation_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._multipleConcatenation_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._multipleConcatenation_ == child)
        {
            this._multipleConcatenation_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._multipleConcatenation_ == oldChild)
        {
            setMultipleConcatenation((PMultipleConcatenation) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
