/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP0CaseItem extends PCaseItem
{
    private PCaseItemEl _caseItemEl_;
    private TTColon _tColon_;
    private PStatementOrNull _statementOrNull_;

    public AP0CaseItem()
    {
        // Constructor
    }

    public AP0CaseItem(
        @SuppressWarnings("hiding") PCaseItemEl _caseItemEl_,
        @SuppressWarnings("hiding") TTColon _tColon_,
        @SuppressWarnings("hiding") PStatementOrNull _statementOrNull_)
    {
        // Constructor
        setCaseItemEl(_caseItemEl_);

        setTColon(_tColon_);

        setStatementOrNull(_statementOrNull_);

    }

    @Override
    public Object clone()
    {
        return new AP0CaseItem(
            cloneNode(this._caseItemEl_),
            cloneNode(this._tColon_),
            cloneNode(this._statementOrNull_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP0CaseItem(this);
    }

    public PCaseItemEl getCaseItemEl()
    {
        return this._caseItemEl_;
    }

    public void setCaseItemEl(PCaseItemEl node)
    {
        if(this._caseItemEl_ != null)
        {
            this._caseItemEl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._caseItemEl_ = node;
    }

    public TTColon getTColon()
    {
        return this._tColon_;
    }

    public void setTColon(TTColon node)
    {
        if(this._tColon_ != null)
        {
            this._tColon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tColon_ = node;
    }

    public PStatementOrNull getStatementOrNull()
    {
        return this._statementOrNull_;
    }

    public void setStatementOrNull(PStatementOrNull node)
    {
        if(this._statementOrNull_ != null)
        {
            this._statementOrNull_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._statementOrNull_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._caseItemEl_)
            + toString(this._tColon_)
            + toString(this._statementOrNull_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._caseItemEl_ == child)
        {
            this._caseItemEl_ = null;
            return;
        }

        if(this._tColon_ == child)
        {
            this._tColon_ = null;
            return;
        }

        if(this._statementOrNull_ == child)
        {
            this._statementOrNull_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._caseItemEl_ == oldChild)
        {
            setCaseItemEl((PCaseItemEl) newChild);
            return;
        }

        if(this._tColon_ == oldChild)
        {
            setTColon((TTColon) newChild);
            return;
        }

        if(this._statementOrNull_ == oldChild)
        {
            setStatementOrNull((PStatementOrNull) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
