/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP0DisableStatement extends PDisableStatement
{
    private TKDisable _kDisable_;
    private PHierarchicalIdentifier _hierarchicalIdentifier_;
    private TTSemicolon _tSemicolon_;

    public AP0DisableStatement()
    {
        // Constructor
    }

    public AP0DisableStatement(
        @SuppressWarnings("hiding") TKDisable _kDisable_,
        @SuppressWarnings("hiding") PHierarchicalIdentifier _hierarchicalIdentifier_,
        @SuppressWarnings("hiding") TTSemicolon _tSemicolon_)
    {
        // Constructor
        setKDisable(_kDisable_);

        setHierarchicalIdentifier(_hierarchicalIdentifier_);

        setTSemicolon(_tSemicolon_);

    }

    @Override
    public Object clone()
    {
        return new AP0DisableStatement(
            cloneNode(this._kDisable_),
            cloneNode(this._hierarchicalIdentifier_),
            cloneNode(this._tSemicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP0DisableStatement(this);
    }

    public TKDisable getKDisable()
    {
        return this._kDisable_;
    }

    public void setKDisable(TKDisable node)
    {
        if(this._kDisable_ != null)
        {
            this._kDisable_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kDisable_ = node;
    }

    public PHierarchicalIdentifier getHierarchicalIdentifier()
    {
        return this._hierarchicalIdentifier_;
    }

    public void setHierarchicalIdentifier(PHierarchicalIdentifier node)
    {
        if(this._hierarchicalIdentifier_ != null)
        {
            this._hierarchicalIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._hierarchicalIdentifier_ = node;
    }

    public TTSemicolon getTSemicolon()
    {
        return this._tSemicolon_;
    }

    public void setTSemicolon(TTSemicolon node)
    {
        if(this._tSemicolon_ != null)
        {
            this._tSemicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tSemicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kDisable_)
            + toString(this._hierarchicalIdentifier_)
            + toString(this._tSemicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kDisable_ == child)
        {
            this._kDisable_ = null;
            return;
        }

        if(this._hierarchicalIdentifier_ == child)
        {
            this._hierarchicalIdentifier_ = null;
            return;
        }

        if(this._tSemicolon_ == child)
        {
            this._tSemicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kDisable_ == oldChild)
        {
            setKDisable((TKDisable) newChild);
            return;
        }

        if(this._hierarchicalIdentifier_ == oldChild)
        {
            setHierarchicalIdentifier((PHierarchicalIdentifier) newChild);
            return;
        }

        if(this._tSemicolon_ == oldChild)
        {
            setTSemicolon((TTSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
