/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP0DelayOrEventControl extends PDelayOrEventControl
{
    private PDelayControl _delayControl_;

    public AP0DelayOrEventControl()
    {
        // Constructor
    }

    public AP0DelayOrEventControl(
        @SuppressWarnings("hiding") PDelayControl _delayControl_)
    {
        // Constructor
        setDelayControl(_delayControl_);

    }

    @Override
    public Object clone()
    {
        return new AP0DelayOrEventControl(
            cloneNode(this._delayControl_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP0DelayOrEventControl(this);
    }

    public PDelayControl getDelayControl()
    {
        return this._delayControl_;
    }

    public void setDelayControl(PDelayControl node)
    {
        if(this._delayControl_ != null)
        {
            this._delayControl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._delayControl_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._delayControl_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._delayControl_ == child)
        {
            this._delayControl_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._delayControl_ == oldChild)
        {
            setDelayControl((PDelayControl) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
