/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP0FunctionRangeOrType extends PFunctionRangeOrType
{
    private TKSigned _kSigned_;
    private PRange _range_;

    public AP0FunctionRangeOrType()
    {
        // Constructor
    }

    public AP0FunctionRangeOrType(
        @SuppressWarnings("hiding") TKSigned _kSigned_,
        @SuppressWarnings("hiding") PRange _range_)
    {
        // Constructor
        setKSigned(_kSigned_);

        setRange(_range_);

    }

    @Override
    public Object clone()
    {
        return new AP0FunctionRangeOrType(
            cloneNode(this._kSigned_),
            cloneNode(this._range_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP0FunctionRangeOrType(this);
    }

    public TKSigned getKSigned()
    {
        return this._kSigned_;
    }

    public void setKSigned(TKSigned node)
    {
        if(this._kSigned_ != null)
        {
            this._kSigned_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kSigned_ = node;
    }

    public PRange getRange()
    {
        return this._range_;
    }

    public void setRange(PRange node)
    {
        if(this._range_ != null)
        {
            this._range_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._range_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kSigned_)
            + toString(this._range_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kSigned_ == child)
        {
            this._kSigned_ = null;
            return;
        }

        if(this._range_ == child)
        {
            this._range_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kSigned_ == oldChild)
        {
            setKSigned((TKSigned) newChild);
            return;
        }

        if(this._range_ == oldChild)
        {
            setRange((PRange) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
