/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP0ListOfSpecparamAssignments extends PListOfSpecparamAssignments
{
    private PSpecparamAssignment _specparamAssignment_;

    public AP0ListOfSpecparamAssignments()
    {
        // Constructor
    }

    public AP0ListOfSpecparamAssignments(
        @SuppressWarnings("hiding") PSpecparamAssignment _specparamAssignment_)
    {
        // Constructor
        setSpecparamAssignment(_specparamAssignment_);

    }

    @Override
    public Object clone()
    {
        return new AP0ListOfSpecparamAssignments(
            cloneNode(this._specparamAssignment_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP0ListOfSpecparamAssignments(this);
    }

    public PSpecparamAssignment getSpecparamAssignment()
    {
        return this._specparamAssignment_;
    }

    public void setSpecparamAssignment(PSpecparamAssignment node)
    {
        if(this._specparamAssignment_ != null)
        {
            this._specparamAssignment_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._specparamAssignment_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._specparamAssignment_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._specparamAssignment_ == child)
        {
            this._specparamAssignment_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._specparamAssignment_ == oldChild)
        {
            setSpecparamAssignment((PSpecparamAssignment) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
