/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP0ListOfParameterAssignments extends PListOfParameterAssignments
{
    private POrderedParameterAssignments _orderedParameterAssignments_;

    public AP0ListOfParameterAssignments()
    {
        // Constructor
    }

    public AP0ListOfParameterAssignments(
        @SuppressWarnings("hiding") POrderedParameterAssignments _orderedParameterAssignments_)
    {
        // Constructor
        setOrderedParameterAssignments(_orderedParameterAssignments_);

    }

    @Override
    public Object clone()
    {
        return new AP0ListOfParameterAssignments(
            cloneNode(this._orderedParameterAssignments_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP0ListOfParameterAssignments(this);
    }

    public POrderedParameterAssignments getOrderedParameterAssignments()
    {
        return this._orderedParameterAssignments_;
    }

    public void setOrderedParameterAssignments(POrderedParameterAssignments node)
    {
        if(this._orderedParameterAssignments_ != null)
        {
            this._orderedParameterAssignments_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._orderedParameterAssignments_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._orderedParameterAssignments_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._orderedParameterAssignments_ == child)
        {
            this._orderedParameterAssignments_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._orderedParameterAssignments_ == oldChild)
        {
            setOrderedParameterAssignments((POrderedParameterAssignments) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
