/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP0ModulePathMintypmaxExpression extends PModulePathMintypmaxExpression
{
    private PModulePathExpression _modulePathExpression_;

    public AP0ModulePathMintypmaxExpression()
    {
        // Constructor
    }

    public AP0ModulePathMintypmaxExpression(
        @SuppressWarnings("hiding") PModulePathExpression _modulePathExpression_)
    {
        // Constructor
        setModulePathExpression(_modulePathExpression_);

    }

    @Override
    public Object clone()
    {
        return new AP0ModulePathMintypmaxExpression(
            cloneNode(this._modulePathExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP0ModulePathMintypmaxExpression(this);
    }

    public PModulePathExpression getModulePathExpression()
    {
        return this._modulePathExpression_;
    }

    public void setModulePathExpression(PModulePathExpression node)
    {
        if(this._modulePathExpression_ != null)
        {
            this._modulePathExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._modulePathExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._modulePathExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._modulePathExpression_ == child)
        {
            this._modulePathExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._modulePathExpression_ == oldChild)
        {
            setModulePathExpression((PModulePathExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
