/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP0PassSwitchtype extends PPassSwitchtype
{
    private TKTran _kTran_;

    public AP0PassSwitchtype()
    {
        // Constructor
    }

    public AP0PassSwitchtype(
        @SuppressWarnings("hiding") TKTran _kTran_)
    {
        // Constructor
        setKTran(_kTran_);

    }

    @Override
    public Object clone()
    {
        return new AP0PassSwitchtype(
            cloneNode(this._kTran_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP0PassSwitchtype(this);
    }

    public TKTran getKTran()
    {
        return this._kTran_;
    }

    public void setKTran(TKTran node)
    {
        if(this._kTran_ != null)
        {
            this._kTran_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kTran_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kTran_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kTran_ == child)
        {
            this._kTran_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kTran_ == oldChild)
        {
            setKTran((TKTran) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
