/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP0PassSwitchInstances extends PPassSwitchInstances
{
    private PPassSwitchInstance _passSwitchInstance_;

    public AP0PassSwitchInstances()
    {
        // Constructor
    }

    public AP0PassSwitchInstances(
        @SuppressWarnings("hiding") PPassSwitchInstance _passSwitchInstance_)
    {
        // Constructor
        setPassSwitchInstance(_passSwitchInstance_);

    }

    @Override
    public Object clone()
    {
        return new AP0PassSwitchInstances(
            cloneNode(this._passSwitchInstance_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP0PassSwitchInstances(this);
    }

    public PPassSwitchInstance getPassSwitchInstance()
    {
        return this._passSwitchInstance_;
    }

    public void setPassSwitchInstance(PPassSwitchInstance node)
    {
        if(this._passSwitchInstance_ != null)
        {
            this._passSwitchInstance_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._passSwitchInstance_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._passSwitchInstance_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._passSwitchInstance_ == child)
        {
            this._passSwitchInstance_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._passSwitchInstance_ == oldChild)
        {
            setPassSwitchInstance((PPassSwitchInstance) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
