/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP0PortDeclarationFoo extends PPortDeclarationFoo
{
    private PPortDeclarationSingle _portDeclarationSingle_;

    public AP0PortDeclarationFoo()
    {
        // Constructor
    }

    public AP0PortDeclarationFoo(
        @SuppressWarnings("hiding") PPortDeclarationSingle _portDeclarationSingle_)
    {
        // Constructor
        setPortDeclarationSingle(_portDeclarationSingle_);

    }

    @Override
    public Object clone()
    {
        return new AP0PortDeclarationFoo(
            cloneNode(this._portDeclarationSingle_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP0PortDeclarationFoo(this);
    }

    public PPortDeclarationSingle getPortDeclarationSingle()
    {
        return this._portDeclarationSingle_;
    }

    public void setPortDeclarationSingle(PPortDeclarationSingle node)
    {
        if(this._portDeclarationSingle_ != null)
        {
            this._portDeclarationSingle_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._portDeclarationSingle_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._portDeclarationSingle_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._portDeclarationSingle_ == child)
        {
            this._portDeclarationSingle_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._portDeclarationSingle_ == oldChild)
        {
            setPortDeclarationSingle((PPortDeclarationSingle) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
