/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP0StatementWithoutTrailingSubstatement extends PStatementWithoutTrailingSubstatement
{
    private PBlockingAssignment _blockingAssignment_;
    private TTSemicolon _tSemicolon_;

    public AP0StatementWithoutTrailingSubstatement()
    {
        // Constructor
    }

    public AP0StatementWithoutTrailingSubstatement(
        @SuppressWarnings("hiding") PBlockingAssignment _blockingAssignment_,
        @SuppressWarnings("hiding") TTSemicolon _tSemicolon_)
    {
        // Constructor
        setBlockingAssignment(_blockingAssignment_);

        setTSemicolon(_tSemicolon_);

    }

    @Override
    public Object clone()
    {
        return new AP0StatementWithoutTrailingSubstatement(
            cloneNode(this._blockingAssignment_),
            cloneNode(this._tSemicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP0StatementWithoutTrailingSubstatement(this);
    }

    public PBlockingAssignment getBlockingAssignment()
    {
        return this._blockingAssignment_;
    }

    public void setBlockingAssignment(PBlockingAssignment node)
    {
        if(this._blockingAssignment_ != null)
        {
            this._blockingAssignment_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._blockingAssignment_ = node;
    }

    public TTSemicolon getTSemicolon()
    {
        return this._tSemicolon_;
    }

    public void setTSemicolon(TTSemicolon node)
    {
        if(this._tSemicolon_ != null)
        {
            this._tSemicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tSemicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._blockingAssignment_)
            + toString(this._tSemicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._blockingAssignment_ == child)
        {
            this._blockingAssignment_ = null;
            return;
        }

        if(this._tSemicolon_ == child)
        {
            this._tSemicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._blockingAssignment_ == oldChild)
        {
            setBlockingAssignment((PBlockingAssignment) newChild);
            return;
        }

        if(this._tSemicolon_ == oldChild)
        {
            setTSemicolon((TTSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
