/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP10SystemTimingCheck extends PSystemTimingCheck
{
    private PWidthTimingCheck _widthTimingCheck_;

    public AP10SystemTimingCheck()
    {
        // Constructor
    }

    public AP10SystemTimingCheck(
        @SuppressWarnings("hiding") PWidthTimingCheck _widthTimingCheck_)
    {
        // Constructor
        setWidthTimingCheck(_widthTimingCheck_);

    }

    @Override
    public Object clone()
    {
        return new AP10SystemTimingCheck(
            cloneNode(this._widthTimingCheck_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP10SystemTimingCheck(this);
    }

    public PWidthTimingCheck getWidthTimingCheck()
    {
        return this._widthTimingCheck_;
    }

    public void setWidthTimingCheck(PWidthTimingCheck node)
    {
        if(this._widthTimingCheck_ != null)
        {
            this._widthTimingCheck_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._widthTimingCheck_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._widthTimingCheck_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._widthTimingCheck_ == child)
        {
            this._widthTimingCheck_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._widthTimingCheck_ == oldChild)
        {
            setWidthTimingCheck((PWidthTimingCheck) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
