/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP1BinaryOperator extends PBinaryOperator
{
    private TTMinus _tMinus_;

    public AP1BinaryOperator()
    {
        // Constructor
    }

    public AP1BinaryOperator(
        @SuppressWarnings("hiding") TTMinus _tMinus_)
    {
        // Constructor
        setTMinus(_tMinus_);

    }

    @Override
    public Object clone()
    {
        return new AP1BinaryOperator(
            cloneNode(this._tMinus_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP1BinaryOperator(this);
    }

    public TTMinus getTMinus()
    {
        return this._tMinus_;
    }

    public void setTMinus(TTMinus node)
    {
        if(this._tMinus_ != null)
        {
            this._tMinus_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tMinus_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tMinus_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tMinus_ == child)
        {
            this._tMinus_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tMinus_ == oldChild)
        {
            setTMinus((TTMinus) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
