/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP1BlockItemDeclaration extends PBlockItemDeclaration
{
    private TKInteger _kInteger_;
    private PListOfBlockVariableIdentifiers _listOfBlockVariableIdentifiers_;
    private TTSemicolon _tSemicolon_;

    public AP1BlockItemDeclaration()
    {
        // Constructor
    }

    public AP1BlockItemDeclaration(
        @SuppressWarnings("hiding") TKInteger _kInteger_,
        @SuppressWarnings("hiding") PListOfBlockVariableIdentifiers _listOfBlockVariableIdentifiers_,
        @SuppressWarnings("hiding") TTSemicolon _tSemicolon_)
    {
        // Constructor
        setKInteger(_kInteger_);

        setListOfBlockVariableIdentifiers(_listOfBlockVariableIdentifiers_);

        setTSemicolon(_tSemicolon_);

    }

    @Override
    public Object clone()
    {
        return new AP1BlockItemDeclaration(
            cloneNode(this._kInteger_),
            cloneNode(this._listOfBlockVariableIdentifiers_),
            cloneNode(this._tSemicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP1BlockItemDeclaration(this);
    }

    public TKInteger getKInteger()
    {
        return this._kInteger_;
    }

    public void setKInteger(TKInteger node)
    {
        if(this._kInteger_ != null)
        {
            this._kInteger_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kInteger_ = node;
    }

    public PListOfBlockVariableIdentifiers getListOfBlockVariableIdentifiers()
    {
        return this._listOfBlockVariableIdentifiers_;
    }

    public void setListOfBlockVariableIdentifiers(PListOfBlockVariableIdentifiers node)
    {
        if(this._listOfBlockVariableIdentifiers_ != null)
        {
            this._listOfBlockVariableIdentifiers_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listOfBlockVariableIdentifiers_ = node;
    }

    public TTSemicolon getTSemicolon()
    {
        return this._tSemicolon_;
    }

    public void setTSemicolon(TTSemicolon node)
    {
        if(this._tSemicolon_ != null)
        {
            this._tSemicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tSemicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kInteger_)
            + toString(this._listOfBlockVariableIdentifiers_)
            + toString(this._tSemicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kInteger_ == child)
        {
            this._kInteger_ = null;
            return;
        }

        if(this._listOfBlockVariableIdentifiers_ == child)
        {
            this._listOfBlockVariableIdentifiers_ = null;
            return;
        }

        if(this._tSemicolon_ == child)
        {
            this._tSemicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kInteger_ == oldChild)
        {
            setKInteger((TKInteger) newChild);
            return;
        }

        if(this._listOfBlockVariableIdentifiers_ == oldChild)
        {
            setListOfBlockVariableIdentifiers((PListOfBlockVariableIdentifiers) newChild);
            return;
        }

        if(this._tSemicolon_ == oldChild)
        {
            setTSemicolon((TTSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
