/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP1FunctionPortList extends PFunctionPortList
{
    private PFunctionPortListItem _functionPortListItem_;

    public AP1FunctionPortList()
    {
        // Constructor
    }

    public AP1FunctionPortList(
        @SuppressWarnings("hiding") PFunctionPortListItem _functionPortListItem_)
    {
        // Constructor
        setFunctionPortListItem(_functionPortListItem_);

    }

    @Override
    public Object clone()
    {
        return new AP1FunctionPortList(
            cloneNode(this._functionPortListItem_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP1FunctionPortList(this);
    }

    public PFunctionPortListItem getFunctionPortListItem()
    {
        return this._functionPortListItem_;
    }

    public void setFunctionPortListItem(PFunctionPortListItem node)
    {
        if(this._functionPortListItem_ != null)
        {
            this._functionPortListItem_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._functionPortListItem_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._functionPortListItem_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._functionPortListItem_ == child)
        {
            this._functionPortListItem_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._functionPortListItem_ == oldChild)
        {
            setFunctionPortListItem((PFunctionPortListItem) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
