/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP1NOutputGatetype extends PNOutputGatetype
{
    private TKNot _kNot_;

    public AP1NOutputGatetype()
    {
        // Constructor
    }

    public AP1NOutputGatetype(
        @SuppressWarnings("hiding") TKNot _kNot_)
    {
        // Constructor
        setKNot(_kNot_);

    }

    @Override
    public Object clone()
    {
        return new AP1NOutputGatetype(
            cloneNode(this._kNot_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP1NOutputGatetype(this);
    }

    public TKNot getKNot()
    {
        return this._kNot_;
    }

    public void setKNot(TKNot node)
    {
        if(this._kNot_ != null)
        {
            this._kNot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kNot_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kNot_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kNot_ == child)
        {
            this._kNot_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kNot_ == oldChild)
        {
            setKNot((TKNot) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
