/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP1PulsestyleDeclaration extends PPulsestyleDeclaration
{
    private TKPulsestyleOndetect _kPulsestyleOndetect_;
    private PListOfPathDescriptors _listOfPathDescriptors_;
    private TTSemicolon _tSemicolon_;

    public AP1PulsestyleDeclaration()
    {
        // Constructor
    }

    public AP1PulsestyleDeclaration(
        @SuppressWarnings("hiding") TKPulsestyleOndetect _kPulsestyleOndetect_,
        @SuppressWarnings("hiding") PListOfPathDescriptors _listOfPathDescriptors_,
        @SuppressWarnings("hiding") TTSemicolon _tSemicolon_)
    {
        // Constructor
        setKPulsestyleOndetect(_kPulsestyleOndetect_);

        setListOfPathDescriptors(_listOfPathDescriptors_);

        setTSemicolon(_tSemicolon_);

    }

    @Override
    public Object clone()
    {
        return new AP1PulsestyleDeclaration(
            cloneNode(this._kPulsestyleOndetect_),
            cloneNode(this._listOfPathDescriptors_),
            cloneNode(this._tSemicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP1PulsestyleDeclaration(this);
    }

    public TKPulsestyleOndetect getKPulsestyleOndetect()
    {
        return this._kPulsestyleOndetect_;
    }

    public void setKPulsestyleOndetect(TKPulsestyleOndetect node)
    {
        if(this._kPulsestyleOndetect_ != null)
        {
            this._kPulsestyleOndetect_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kPulsestyleOndetect_ = node;
    }

    public PListOfPathDescriptors getListOfPathDescriptors()
    {
        return this._listOfPathDescriptors_;
    }

    public void setListOfPathDescriptors(PListOfPathDescriptors node)
    {
        if(this._listOfPathDescriptors_ != null)
        {
            this._listOfPathDescriptors_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listOfPathDescriptors_ = node;
    }

    public TTSemicolon getTSemicolon()
    {
        return this._tSemicolon_;
    }

    public void setTSemicolon(TTSemicolon node)
    {
        if(this._tSemicolon_ != null)
        {
            this._tSemicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tSemicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kPulsestyleOndetect_)
            + toString(this._listOfPathDescriptors_)
            + toString(this._tSemicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kPulsestyleOndetect_ == child)
        {
            this._kPulsestyleOndetect_ = null;
            return;
        }

        if(this._listOfPathDescriptors_ == child)
        {
            this._listOfPathDescriptors_ = null;
            return;
        }

        if(this._tSemicolon_ == child)
        {
            this._tSemicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kPulsestyleOndetect_ == oldChild)
        {
            setKPulsestyleOndetect((TKPulsestyleOndetect) newChild);
            return;
        }

        if(this._listOfPathDescriptors_ == oldChild)
        {
            setListOfPathDescriptors((PListOfPathDescriptors) newChild);
            return;
        }

        if(this._tSemicolon_ == oldChild)
        {
            setTSemicolon((TTSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
