/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP1PortDeclaration extends PPortDeclaration
{
    private PInputDeclaration _inputDeclaration_;

    public AP1PortDeclaration()
    {
        // Constructor
    }

    public AP1PortDeclaration(
        @SuppressWarnings("hiding") PInputDeclaration _inputDeclaration_)
    {
        // Constructor
        setInputDeclaration(_inputDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AP1PortDeclaration(
            cloneNode(this._inputDeclaration_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP1PortDeclaration(this);
    }

    public PInputDeclaration getInputDeclaration()
    {
        return this._inputDeclaration_;
    }

    public void setInputDeclaration(PInputDeclaration node)
    {
        if(this._inputDeclaration_ != null)
        {
            this._inputDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._inputDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._inputDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._inputDeclaration_ == child)
        {
            this._inputDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._inputDeclaration_ == oldChild)
        {
            setInputDeclaration((PInputDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
