/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP1PassEnSwitchtype extends PPassEnSwitchtype
{
    private TKTranif1 _kTranif1_;

    public AP1PassEnSwitchtype()
    {
        // Constructor
    }

    public AP1PassEnSwitchtype(
        @SuppressWarnings("hiding") TKTranif1 _kTranif1_)
    {
        // Constructor
        setKTranif1(_kTranif1_);

    }

    @Override
    public Object clone()
    {
        return new AP1PassEnSwitchtype(
            cloneNode(this._kTranif1_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP1PassEnSwitchtype(this);
    }

    public TKTranif1 getKTranif1()
    {
        return this._kTranif1_;
    }

    public void setKTranif1(TKTranif1 node)
    {
        if(this._kTranif1_ != null)
        {
            this._kTranif1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kTranif1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kTranif1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kTranif1_ == child)
        {
            this._kTranif1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kTranif1_ == oldChild)
        {
            setKTranif1((TKTranif1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
