/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP1PullGateInstances extends PPullGateInstances
{
    private PPullGateInstance _pullGateInstance_;
    private TTComma _tComma_;
    private PPullGateInstances _pullGateInstances_;

    public AP1PullGateInstances()
    {
        // Constructor
    }

    public AP1PullGateInstances(
        @SuppressWarnings("hiding") PPullGateInstance _pullGateInstance_,
        @SuppressWarnings("hiding") TTComma _tComma_,
        @SuppressWarnings("hiding") PPullGateInstances _pullGateInstances_)
    {
        // Constructor
        setPullGateInstance(_pullGateInstance_);

        setTComma(_tComma_);

        setPullGateInstances(_pullGateInstances_);

    }

    @Override
    public Object clone()
    {
        return new AP1PullGateInstances(
            cloneNode(this._pullGateInstance_),
            cloneNode(this._tComma_),
            cloneNode(this._pullGateInstances_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP1PullGateInstances(this);
    }

    public PPullGateInstance getPullGateInstance()
    {
        return this._pullGateInstance_;
    }

    public void setPullGateInstance(PPullGateInstance node)
    {
        if(this._pullGateInstance_ != null)
        {
            this._pullGateInstance_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pullGateInstance_ = node;
    }

    public TTComma getTComma()
    {
        return this._tComma_;
    }

    public void setTComma(TTComma node)
    {
        if(this._tComma_ != null)
        {
            this._tComma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tComma_ = node;
    }

    public PPullGateInstances getPullGateInstances()
    {
        return this._pullGateInstances_;
    }

    public void setPullGateInstances(PPullGateInstances node)
    {
        if(this._pullGateInstances_ != null)
        {
            this._pullGateInstances_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pullGateInstances_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._pullGateInstance_)
            + toString(this._tComma_)
            + toString(this._pullGateInstances_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._pullGateInstance_ == child)
        {
            this._pullGateInstance_ = null;
            return;
        }

        if(this._tComma_ == child)
        {
            this._tComma_ = null;
            return;
        }

        if(this._pullGateInstances_ == child)
        {
            this._pullGateInstances_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._pullGateInstance_ == oldChild)
        {
            setPullGateInstance((PPullGateInstance) newChild);
            return;
        }

        if(this._tComma_ == oldChild)
        {
            setTComma((TTComma) newChild);
            return;
        }

        if(this._pullGateInstances_ == oldChild)
        {
            setPullGateInstances((PPullGateInstances) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
