/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP1StatementNoShortIf extends PStatementNoShortIf
{
    private PIfThenElseStatementNsf _ifThenElseStatementNsf_;

    public AP1StatementNoShortIf()
    {
        // Constructor
    }

    public AP1StatementNoShortIf(
        @SuppressWarnings("hiding") PIfThenElseStatementNsf _ifThenElseStatementNsf_)
    {
        // Constructor
        setIfThenElseStatementNsf(_ifThenElseStatementNsf_);

    }

    @Override
    public Object clone()
    {
        return new AP1StatementNoShortIf(
            cloneNode(this._ifThenElseStatementNsf_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP1StatementNoShortIf(this);
    }

    public PIfThenElseStatementNsf getIfThenElseStatementNsf()
    {
        return this._ifThenElseStatementNsf_;
    }

    public void setIfThenElseStatementNsf(PIfThenElseStatementNsf node)
    {
        if(this._ifThenElseStatementNsf_ != null)
        {
            this._ifThenElseStatementNsf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifThenElseStatementNsf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ifThenElseStatementNsf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ifThenElseStatementNsf_ == child)
        {
            this._ifThenElseStatementNsf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ifThenElseStatementNsf_ == oldChild)
        {
            setIfThenElseStatementNsf((PIfThenElseStatementNsf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
