/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP1SystemTaskEnable extends PSystemTaskEnable
{
    private TSystemFunctionIdentifier _systemFunctionIdentifier_;
    private TTLparen _tLparen_;
    private PTaskEnableEl _taskEnableEl_;
    private TTRparen _tRparen_;
    private TTSemicolon _tSemicolon_;

    public AP1SystemTaskEnable()
    {
        // Constructor
    }

    public AP1SystemTaskEnable(
        @SuppressWarnings("hiding") TSystemFunctionIdentifier _systemFunctionIdentifier_,
        @SuppressWarnings("hiding") TTLparen _tLparen_,
        @SuppressWarnings("hiding") PTaskEnableEl _taskEnableEl_,
        @SuppressWarnings("hiding") TTRparen _tRparen_,
        @SuppressWarnings("hiding") TTSemicolon _tSemicolon_)
    {
        // Constructor
        setSystemFunctionIdentifier(_systemFunctionIdentifier_);

        setTLparen(_tLparen_);

        setTaskEnableEl(_taskEnableEl_);

        setTRparen(_tRparen_);

        setTSemicolon(_tSemicolon_);

    }

    @Override
    public Object clone()
    {
        return new AP1SystemTaskEnable(
            cloneNode(this._systemFunctionIdentifier_),
            cloneNode(this._tLparen_),
            cloneNode(this._taskEnableEl_),
            cloneNode(this._tRparen_),
            cloneNode(this._tSemicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP1SystemTaskEnable(this);
    }

    public TSystemFunctionIdentifier getSystemFunctionIdentifier()
    {
        return this._systemFunctionIdentifier_;
    }

    public void setSystemFunctionIdentifier(TSystemFunctionIdentifier node)
    {
        if(this._systemFunctionIdentifier_ != null)
        {
            this._systemFunctionIdentifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._systemFunctionIdentifier_ = node;
    }

    public TTLparen getTLparen()
    {
        return this._tLparen_;
    }

    public void setTLparen(TTLparen node)
    {
        if(this._tLparen_ != null)
        {
            this._tLparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tLparen_ = node;
    }

    public PTaskEnableEl getTaskEnableEl()
    {
        return this._taskEnableEl_;
    }

    public void setTaskEnableEl(PTaskEnableEl node)
    {
        if(this._taskEnableEl_ != null)
        {
            this._taskEnableEl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._taskEnableEl_ = node;
    }

    public TTRparen getTRparen()
    {
        return this._tRparen_;
    }

    public void setTRparen(TTRparen node)
    {
        if(this._tRparen_ != null)
        {
            this._tRparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tRparen_ = node;
    }

    public TTSemicolon getTSemicolon()
    {
        return this._tSemicolon_;
    }

    public void setTSemicolon(TTSemicolon node)
    {
        if(this._tSemicolon_ != null)
        {
            this._tSemicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tSemicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._systemFunctionIdentifier_)
            + toString(this._tLparen_)
            + toString(this._taskEnableEl_)
            + toString(this._tRparen_)
            + toString(this._tSemicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._systemFunctionIdentifier_ == child)
        {
            this._systemFunctionIdentifier_ = null;
            return;
        }

        if(this._tLparen_ == child)
        {
            this._tLparen_ = null;
            return;
        }

        if(this._taskEnableEl_ == child)
        {
            this._taskEnableEl_ = null;
            return;
        }

        if(this._tRparen_ == child)
        {
            this._tRparen_ = null;
            return;
        }

        if(this._tSemicolon_ == child)
        {
            this._tSemicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._systemFunctionIdentifier_ == oldChild)
        {
            setSystemFunctionIdentifier((TSystemFunctionIdentifier) newChild);
            return;
        }

        if(this._tLparen_ == oldChild)
        {
            setTLparen((TTLparen) newChild);
            return;
        }

        if(this._taskEnableEl_ == oldChild)
        {
            setTaskEnableEl((PTaskEnableEl) newChild);
            return;
        }

        if(this._tRparen_ == oldChild)
        {
            setTRparen((TTRparen) newChild);
            return;
        }

        if(this._tSemicolon_ == oldChild)
        {
            setTSemicolon((TTSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
