/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP1TimingCheckEvent extends PTimingCheckEvent
{
    private PTimingCheckEventControl _timingCheckEventControl_;
    private PSpecifyTerminalDescriptor _specifyTerminalDescriptor_;
    private TTTand _tTand_;
    private PTimingCheckCondition _timingCheckCondition_;

    public AP1TimingCheckEvent()
    {
        // Constructor
    }

    public AP1TimingCheckEvent(
        @SuppressWarnings("hiding") PTimingCheckEventControl _timingCheckEventControl_,
        @SuppressWarnings("hiding") PSpecifyTerminalDescriptor _specifyTerminalDescriptor_,
        @SuppressWarnings("hiding") TTTand _tTand_,
        @SuppressWarnings("hiding") PTimingCheckCondition _timingCheckCondition_)
    {
        // Constructor
        setTimingCheckEventControl(_timingCheckEventControl_);

        setSpecifyTerminalDescriptor(_specifyTerminalDescriptor_);

        setTTand(_tTand_);

        setTimingCheckCondition(_timingCheckCondition_);

    }

    @Override
    public Object clone()
    {
        return new AP1TimingCheckEvent(
            cloneNode(this._timingCheckEventControl_),
            cloneNode(this._specifyTerminalDescriptor_),
            cloneNode(this._tTand_),
            cloneNode(this._timingCheckCondition_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP1TimingCheckEvent(this);
    }

    public PTimingCheckEventControl getTimingCheckEventControl()
    {
        return this._timingCheckEventControl_;
    }

    public void setTimingCheckEventControl(PTimingCheckEventControl node)
    {
        if(this._timingCheckEventControl_ != null)
        {
            this._timingCheckEventControl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._timingCheckEventControl_ = node;
    }

    public PSpecifyTerminalDescriptor getSpecifyTerminalDescriptor()
    {
        return this._specifyTerminalDescriptor_;
    }

    public void setSpecifyTerminalDescriptor(PSpecifyTerminalDescriptor node)
    {
        if(this._specifyTerminalDescriptor_ != null)
        {
            this._specifyTerminalDescriptor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._specifyTerminalDescriptor_ = node;
    }

    public TTTand getTTand()
    {
        return this._tTand_;
    }

    public void setTTand(TTTand node)
    {
        if(this._tTand_ != null)
        {
            this._tTand_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tTand_ = node;
    }

    public PTimingCheckCondition getTimingCheckCondition()
    {
        return this._timingCheckCondition_;
    }

    public void setTimingCheckCondition(PTimingCheckCondition node)
    {
        if(this._timingCheckCondition_ != null)
        {
            this._timingCheckCondition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._timingCheckCondition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._timingCheckEventControl_)
            + toString(this._specifyTerminalDescriptor_)
            + toString(this._tTand_)
            + toString(this._timingCheckCondition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._timingCheckEventControl_ == child)
        {
            this._timingCheckEventControl_ = null;
            return;
        }

        if(this._specifyTerminalDescriptor_ == child)
        {
            this._specifyTerminalDescriptor_ = null;
            return;
        }

        if(this._tTand_ == child)
        {
            this._tTand_ = null;
            return;
        }

        if(this._timingCheckCondition_ == child)
        {
            this._timingCheckCondition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._timingCheckEventControl_ == oldChild)
        {
            setTimingCheckEventControl((PTimingCheckEventControl) newChild);
            return;
        }

        if(this._specifyTerminalDescriptor_ == oldChild)
        {
            setSpecifyTerminalDescriptor((PSpecifyTerminalDescriptor) newChild);
            return;
        }

        if(this._tTand_ == oldChild)
        {
            setTTand((TTTand) newChild);
            return;
        }

        if(this._timingCheckCondition_ == oldChild)
        {
            setTimingCheckCondition((PTimingCheckCondition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
