/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP1TaskPortList extends PTaskPortList
{
    private PTaskPortItem _taskPortItem_;

    public AP1TaskPortList()
    {
        // Constructor
    }

    public AP1TaskPortList(
        @SuppressWarnings("hiding") PTaskPortItem _taskPortItem_)
    {
        // Constructor
        setTaskPortItem(_taskPortItem_);

    }

    @Override
    public Object clone()
    {
        return new AP1TaskPortList(
            cloneNode(this._taskPortItem_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP1TaskPortList(this);
    }

    public PTaskPortItem getTaskPortItem()
    {
        return this._taskPortItem_;
    }

    public void setTaskPortItem(PTaskPortItem node)
    {
        if(this._taskPortItem_ != null)
        {
            this._taskPortItem_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._taskPortItem_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._taskPortItem_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._taskPortItem_ == child)
        {
            this._taskPortItem_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._taskPortItem_ == oldChild)
        {
            setTaskPortItem((PTaskPortItem) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
