/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP2BlockItemDeclaration extends PBlockItemDeclaration
{
    private TKTime _kTime_;
    private PListOfBlockVariableIdentifiers _listOfBlockVariableIdentifiers_;
    private TTSemicolon _tSemicolon_;

    public AP2BlockItemDeclaration()
    {
        // Constructor
    }

    public AP2BlockItemDeclaration(
        @SuppressWarnings("hiding") TKTime _kTime_,
        @SuppressWarnings("hiding") PListOfBlockVariableIdentifiers _listOfBlockVariableIdentifiers_,
        @SuppressWarnings("hiding") TTSemicolon _tSemicolon_)
    {
        // Constructor
        setKTime(_kTime_);

        setListOfBlockVariableIdentifiers(_listOfBlockVariableIdentifiers_);

        setTSemicolon(_tSemicolon_);

    }

    @Override
    public Object clone()
    {
        return new AP2BlockItemDeclaration(
            cloneNode(this._kTime_),
            cloneNode(this._listOfBlockVariableIdentifiers_),
            cloneNode(this._tSemicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP2BlockItemDeclaration(this);
    }

    public TKTime getKTime()
    {
        return this._kTime_;
    }

    public void setKTime(TKTime node)
    {
        if(this._kTime_ != null)
        {
            this._kTime_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kTime_ = node;
    }

    public PListOfBlockVariableIdentifiers getListOfBlockVariableIdentifiers()
    {
        return this._listOfBlockVariableIdentifiers_;
    }

    public void setListOfBlockVariableIdentifiers(PListOfBlockVariableIdentifiers node)
    {
        if(this._listOfBlockVariableIdentifiers_ != null)
        {
            this._listOfBlockVariableIdentifiers_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listOfBlockVariableIdentifiers_ = node;
    }

    public TTSemicolon getTSemicolon()
    {
        return this._tSemicolon_;
    }

    public void setTSemicolon(TTSemicolon node)
    {
        if(this._tSemicolon_ != null)
        {
            this._tSemicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tSemicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kTime_)
            + toString(this._listOfBlockVariableIdentifiers_)
            + toString(this._tSemicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kTime_ == child)
        {
            this._kTime_ = null;
            return;
        }

        if(this._listOfBlockVariableIdentifiers_ == child)
        {
            this._listOfBlockVariableIdentifiers_ = null;
            return;
        }

        if(this._tSemicolon_ == child)
        {
            this._tSemicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kTime_ == oldChild)
        {
            setKTime((TKTime) newChild);
            return;
        }

        if(this._listOfBlockVariableIdentifiers_ == oldChild)
        {
            setListOfBlockVariableIdentifiers((PListOfBlockVariableIdentifiers) newChild);
            return;
        }

        if(this._tSemicolon_ == oldChild)
        {
            setTSemicolon((TTSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
