/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP2EnableGatetype extends PEnableGatetype
{
    private TKNotif0 _kNotif0_;

    public AP2EnableGatetype()
    {
        // Constructor
    }

    public AP2EnableGatetype(
        @SuppressWarnings("hiding") TKNotif0 _kNotif0_)
    {
        // Constructor
        setKNotif0(_kNotif0_);

    }

    @Override
    public Object clone()
    {
        return new AP2EnableGatetype(
            cloneNode(this._kNotif0_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP2EnableGatetype(this);
    }

    public TKNotif0 getKNotif0()
    {
        return this._kNotif0_;
    }

    public void setKNotif0(TKNotif0 node)
    {
        if(this._kNotif0_ != null)
        {
            this._kNotif0_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kNotif0_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kNotif0_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kNotif0_ == child)
        {
            this._kNotif0_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kNotif0_ == oldChild)
        {
            setKNotif0((TKNotif0) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
