/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP2PortDeclaration extends PPortDeclaration
{
    private POutputDeclaration _outputDeclaration_;

    public AP2PortDeclaration()
    {
        // Constructor
    }

    public AP2PortDeclaration(
        @SuppressWarnings("hiding") POutputDeclaration _outputDeclaration_)
    {
        // Constructor
        setOutputDeclaration(_outputDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AP2PortDeclaration(
            cloneNode(this._outputDeclaration_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP2PortDeclaration(this);
    }

    public POutputDeclaration getOutputDeclaration()
    {
        return this._outputDeclaration_;
    }

    public void setOutputDeclaration(POutputDeclaration node)
    {
        if(this._outputDeclaration_ != null)
        {
            this._outputDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._outputDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._outputDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._outputDeclaration_ == child)
        {
            this._outputDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._outputDeclaration_ == oldChild)
        {
            setOutputDeclaration((POutputDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
