/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP2RangeExpression extends PRangeExpression
{
    private PExpression _e1_;
    private TTPlusColon _tPlusColon_;
    private PExpression _e2_;

    public AP2RangeExpression()
    {
        // Constructor
    }

    public AP2RangeExpression(
        @SuppressWarnings("hiding") PExpression _e1_,
        @SuppressWarnings("hiding") TTPlusColon _tPlusColon_,
        @SuppressWarnings("hiding") PExpression _e2_)
    {
        // Constructor
        setE1(_e1_);

        setTPlusColon(_tPlusColon_);

        setE2(_e2_);

    }

    @Override
    public Object clone()
    {
        return new AP2RangeExpression(
            cloneNode(this._e1_),
            cloneNode(this._tPlusColon_),
            cloneNode(this._e2_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP2RangeExpression(this);
    }

    public PExpression getE1()
    {
        return this._e1_;
    }

    public void setE1(PExpression node)
    {
        if(this._e1_ != null)
        {
            this._e1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e1_ = node;
    }

    public TTPlusColon getTPlusColon()
    {
        return this._tPlusColon_;
    }

    public void setTPlusColon(TTPlusColon node)
    {
        if(this._tPlusColon_ != null)
        {
            this._tPlusColon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tPlusColon_ = node;
    }

    public PExpression getE2()
    {
        return this._e2_;
    }

    public void setE2(PExpression node)
    {
        if(this._e2_ != null)
        {
            this._e2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._e1_)
            + toString(this._tPlusColon_)
            + toString(this._e2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._e1_ == child)
        {
            this._e1_ = null;
            return;
        }

        if(this._tPlusColon_ == child)
        {
            this._tPlusColon_ = null;
            return;
        }

        if(this._e2_ == child)
        {
            this._e2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._e1_ == oldChild)
        {
            setE1((PExpression) newChild);
            return;
        }

        if(this._tPlusColon_ == oldChild)
        {
            setTPlusColon((TTPlusColon) newChild);
            return;
        }

        if(this._e2_ == oldChild)
        {
            setE2((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
