/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP2SpecifyItem extends PSpecifyItem
{
    private PShowcancelledDeclaration _showcancelledDeclaration_;

    public AP2SpecifyItem()
    {
        // Constructor
    }

    public AP2SpecifyItem(
        @SuppressWarnings("hiding") PShowcancelledDeclaration _showcancelledDeclaration_)
    {
        // Constructor
        setShowcancelledDeclaration(_showcancelledDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AP2SpecifyItem(
            cloneNode(this._showcancelledDeclaration_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP2SpecifyItem(this);
    }

    public PShowcancelledDeclaration getShowcancelledDeclaration()
    {
        return this._showcancelledDeclaration_;
    }

    public void setShowcancelledDeclaration(PShowcancelledDeclaration node)
    {
        if(this._showcancelledDeclaration_ != null)
        {
            this._showcancelledDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._showcancelledDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._showcancelledDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._showcancelledDeclaration_ == child)
        {
            this._showcancelledDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._showcancelledDeclaration_ == oldChild)
        {
            setShowcancelledDeclaration((PShowcancelledDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
