/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP2Strength0 extends PStrength0
{
    private TKPull0 _kPull0_;

    public AP2Strength0()
    {
        // Constructor
    }

    public AP2Strength0(
        @SuppressWarnings("hiding") TKPull0 _kPull0_)
    {
        // Constructor
        setKPull0(_kPull0_);

    }

    @Override
    public Object clone()
    {
        return new AP2Strength0(
            cloneNode(this._kPull0_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP2Strength0(this);
    }

    public TKPull0 getKPull0()
    {
        return this._kPull0_;
    }

    public void setKPull0(TKPull0 node)
    {
        if(this._kPull0_ != null)
        {
            this._kPull0_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kPull0_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kPull0_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kPull0_ == child)
        {
            this._kPull0_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kPull0_ == oldChild)
        {
            setKPull0((TKPull0) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
