/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP2TimingCheckEventControl extends PTimingCheckEventControl
{
    private PEdgeControlSpecifier _edgeControlSpecifier_;

    public AP2TimingCheckEventControl()
    {
        // Constructor
    }

    public AP2TimingCheckEventControl(
        @SuppressWarnings("hiding") PEdgeControlSpecifier _edgeControlSpecifier_)
    {
        // Constructor
        setEdgeControlSpecifier(_edgeControlSpecifier_);

    }

    @Override
    public Object clone()
    {
        return new AP2TimingCheckEventControl(
            cloneNode(this._edgeControlSpecifier_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP2TimingCheckEventControl(this);
    }

    public PEdgeControlSpecifier getEdgeControlSpecifier()
    {
        return this._edgeControlSpecifier_;
    }

    public void setEdgeControlSpecifier(PEdgeControlSpecifier node)
    {
        if(this._edgeControlSpecifier_ != null)
        {
            this._edgeControlSpecifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._edgeControlSpecifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._edgeControlSpecifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._edgeControlSpecifier_ == child)
        {
            this._edgeControlSpecifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._edgeControlSpecifier_ == oldChild)
        {
            setEdgeControlSpecifier((PEdgeControlSpecifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
