/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP3EnableGatetype extends PEnableGatetype
{
    private TKNotif1 _kNotif1_;

    public AP3EnableGatetype()
    {
        // Constructor
    }

    public AP3EnableGatetype(
        @SuppressWarnings("hiding") TKNotif1 _kNotif1_)
    {
        // Constructor
        setKNotif1(_kNotif1_);

    }

    @Override
    public Object clone()
    {
        return new AP3EnableGatetype(
            cloneNode(this._kNotif1_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP3EnableGatetype(this);
    }

    public TKNotif1 getKNotif1()
    {
        return this._kNotif1_;
    }

    public void setKNotif1(TKNotif1 node)
    {
        if(this._kNotif1_ != null)
        {
            this._kNotif1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kNotif1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kNotif1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kNotif1_ == child)
        {
            this._kNotif1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kNotif1_ == oldChild)
        {
            setKNotif1((TKNotif1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
