/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP3NetType extends PNetType
{
    private TKTriand _kTriand_;

    public AP3NetType()
    {
        // Constructor
    }

    public AP3NetType(
        @SuppressWarnings("hiding") TKTriand _kTriand_)
    {
        // Constructor
        setKTriand(_kTriand_);

    }

    @Override
    public Object clone()
    {
        return new AP3NetType(
            cloneNode(this._kTriand_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP3NetType(this);
    }

    public TKTriand getKTriand()
    {
        return this._kTriand_;
    }

    public void setKTriand(TKTriand node)
    {
        if(this._kTriand_ != null)
        {
            this._kTriand_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kTriand_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kTriand_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kTriand_ == child)
        {
            this._kTriand_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kTriand_ == oldChild)
        {
            setKTriand((TKTriand) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
