/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP3StatementNoShortIf extends PStatementNoShortIf
{
    private PWaitStatementNsf _waitStatementNsf_;

    public AP3StatementNoShortIf()
    {
        // Constructor
    }

    public AP3StatementNoShortIf(
        @SuppressWarnings("hiding") PWaitStatementNsf _waitStatementNsf_)
    {
        // Constructor
        setWaitStatementNsf(_waitStatementNsf_);

    }

    @Override
    public Object clone()
    {
        return new AP3StatementNoShortIf(
            cloneNode(this._waitStatementNsf_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP3StatementNoShortIf(this);
    }

    public PWaitStatementNsf getWaitStatementNsf()
    {
        return this._waitStatementNsf_;
    }

    public void setWaitStatementNsf(PWaitStatementNsf node)
    {
        if(this._waitStatementNsf_ != null)
        {
            this._waitStatementNsf_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._waitStatementNsf_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._waitStatementNsf_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._waitStatementNsf_ == child)
        {
            this._waitStatementNsf_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._waitStatementNsf_ == oldChild)
        {
            setWaitStatementNsf((PWaitStatementNsf) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
