/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP4NInputGatetype extends PNInputGatetype
{
    private TKXor _kXor_;

    public AP4NInputGatetype()
    {
        // Constructor
    }

    public AP4NInputGatetype(
        @SuppressWarnings("hiding") TKXor _kXor_)
    {
        // Constructor
        setKXor(_kXor_);

    }

    @Override
    public Object clone()
    {
        return new AP4NInputGatetype(
            cloneNode(this._kXor_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP4NInputGatetype(this);
    }

    public TKXor getKXor()
    {
        return this._kXor_;
    }

    public void setKXor(TKXor node)
    {
        if(this._kXor_ != null)
        {
            this._kXor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kXor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kXor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kXor_ == child)
        {
            this._kXor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kXor_ == oldChild)
        {
            setKXor((TKXor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
