/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP5NInputGatetype extends PNInputGatetype
{
    private TKXnor _kXnor_;

    public AP5NInputGatetype()
    {
        // Constructor
    }

    public AP5NInputGatetype(
        @SuppressWarnings("hiding") TKXnor _kXnor_)
    {
        // Constructor
        setKXnor(_kXnor_);

    }

    @Override
    public Object clone()
    {
        return new AP5NInputGatetype(
            cloneNode(this._kXnor_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP5NInputGatetype(this);
    }

    public TKXnor getKXnor()
    {
        return this._kXnor_;
    }

    public void setKXnor(TKXnor node)
    {
        if(this._kXnor_ != null)
        {
            this._kXnor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kXnor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kXnor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kXnor_ == child)
        {
            this._kXnor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kXnor_ == oldChild)
        {
            setKXnor((TKXnor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
