/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP5StatementWithoutTrailingSubstatement extends PStatementWithoutTrailingSubstatement
{
    private PParBlock _parBlock_;

    public AP5StatementWithoutTrailingSubstatement()
    {
        // Constructor
    }

    public AP5StatementWithoutTrailingSubstatement(
        @SuppressWarnings("hiding") PParBlock _parBlock_)
    {
        // Constructor
        setParBlock(_parBlock_);

    }

    @Override
    public Object clone()
    {
        return new AP5StatementWithoutTrailingSubstatement(
            cloneNode(this._parBlock_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP5StatementWithoutTrailingSubstatement(this);
    }

    public PParBlock getParBlock()
    {
        return this._parBlock_;
    }

    public void setParBlock(PParBlock node)
    {
        if(this._parBlock_ != null)
        {
            this._parBlock_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parBlock_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parBlock_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parBlock_ == child)
        {
            this._parBlock_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._parBlock_ == oldChild)
        {
            setParBlock((PParBlock) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
