/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP6NetType extends PNetType
{
    private TKTri1 _kTri1_;

    public AP6NetType()
    {
        // Constructor
    }

    public AP6NetType(
        @SuppressWarnings("hiding") TKTri1 _kTri1_)
    {
        // Constructor
        setKTri1(_kTri1_);

    }

    @Override
    public Object clone()
    {
        return new AP6NetType(
            cloneNode(this._kTri1_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP6NetType(this);
    }

    public TKTri1 getKTri1()
    {
        return this._kTri1_;
    }

    public void setKTri1(TKTri1 node)
    {
        if(this._kTri1_ != null)
        {
            this._kTri1_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kTri1_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kTri1_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kTri1_ == child)
        {
            this._kTri1_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kTri1_ == oldChild)
        {
            setKTri1((TKTri1) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
