/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP7NetType extends PNetType
{
    private TKUwire _kUwire_;

    public AP7NetType()
    {
        // Constructor
    }

    public AP7NetType(
        @SuppressWarnings("hiding") TKUwire _kUwire_)
    {
        // Constructor
        setKUwire(_kUwire_);

    }

    @Override
    public Object clone()
    {
        return new AP7NetType(
            cloneNode(this._kUwire_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP7NetType(this);
    }

    public TKUwire getKUwire()
    {
        return this._kUwire_;
    }

    public void setKUwire(TKUwire node)
    {
        if(this._kUwire_ != null)
        {
            this._kUwire_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kUwire_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kUwire_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kUwire_ == child)
        {
            this._kUwire_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kUwire_ == oldChild)
        {
            setKUwire((TKUwire) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
