/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP7UnaryModulePathOperator extends PUnaryModulePathOperator
{
    private TTNxor _tNxor_;

    public AP7UnaryModulePathOperator()
    {
        // Constructor
    }

    public AP7UnaryModulePathOperator(
        @SuppressWarnings("hiding") TTNxor _tNxor_)
    {
        // Constructor
        setTNxor(_tNxor_);

    }

    @Override
    public Object clone()
    {
        return new AP7UnaryModulePathOperator(
            cloneNode(this._tNxor_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP7UnaryModulePathOperator(this);
    }

    public TTNxor getTNxor()
    {
        return this._tNxor_;
    }

    public void setTNxor(TTNxor node)
    {
        if(this._tNxor_ != null)
        {
            this._tNxor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tNxor_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tNxor_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tNxor_ == child)
        {
            this._tNxor_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tNxor_ == oldChild)
        {
            setTNxor((TTNxor) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
