/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AP9NetType extends PNetType
{
    private TKWand _kWand_;

    public AP9NetType()
    {
        // Constructor
    }

    public AP9NetType(
        @SuppressWarnings("hiding") TKWand _kWand_)
    {
        // Constructor
        setKWand(_kWand_);

    }

    @Override
    public Object clone()
    {
        return new AP9NetType(
            cloneNode(this._kWand_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAP9NetType(this);
    }

    public TKWand getKWand()
    {
        return this._kWand_;
    }

    public void setKWand(TKWand node)
    {
        if(this._kWand_ != null)
        {
            this._kWand_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kWand_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kWand_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kWand_ == child)
        {
            this._kWand_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kWand_ == oldChild)
        {
            setKWand((TKWand) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
