/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AParameterValueAssignment extends PParameterValueAssignment
{
    private TTHash _tHash_;
    private TTLparen _tLparen_;
    private PListOfParameterAssignments _listOfParameterAssignments_;
    private TTRparen _tRparen_;

    public AParameterValueAssignment()
    {
        // Constructor
    }

    public AParameterValueAssignment(
        @SuppressWarnings("hiding") TTHash _tHash_,
        @SuppressWarnings("hiding") TTLparen _tLparen_,
        @SuppressWarnings("hiding") PListOfParameterAssignments _listOfParameterAssignments_,
        @SuppressWarnings("hiding") TTRparen _tRparen_)
    {
        // Constructor
        setTHash(_tHash_);

        setTLparen(_tLparen_);

        setListOfParameterAssignments(_listOfParameterAssignments_);

        setTRparen(_tRparen_);

    }

    @Override
    public Object clone()
    {
        return new AParameterValueAssignment(
            cloneNode(this._tHash_),
            cloneNode(this._tLparen_),
            cloneNode(this._listOfParameterAssignments_),
            cloneNode(this._tRparen_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAParameterValueAssignment(this);
    }

    public TTHash getTHash()
    {
        return this._tHash_;
    }

    public void setTHash(TTHash node)
    {
        if(this._tHash_ != null)
        {
            this._tHash_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tHash_ = node;
    }

    public TTLparen getTLparen()
    {
        return this._tLparen_;
    }

    public void setTLparen(TTLparen node)
    {
        if(this._tLparen_ != null)
        {
            this._tLparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tLparen_ = node;
    }

    public PListOfParameterAssignments getListOfParameterAssignments()
    {
        return this._listOfParameterAssignments_;
    }

    public void setListOfParameterAssignments(PListOfParameterAssignments node)
    {
        if(this._listOfParameterAssignments_ != null)
        {
            this._listOfParameterAssignments_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listOfParameterAssignments_ = node;
    }

    public TTRparen getTRparen()
    {
        return this._tRparen_;
    }

    public void setTRparen(TTRparen node)
    {
        if(this._tRparen_ != null)
        {
            this._tRparen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tRparen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tHash_)
            + toString(this._tLparen_)
            + toString(this._listOfParameterAssignments_)
            + toString(this._tRparen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tHash_ == child)
        {
            this._tHash_ = null;
            return;
        }

        if(this._tLparen_ == child)
        {
            this._tLparen_ = null;
            return;
        }

        if(this._listOfParameterAssignments_ == child)
        {
            this._listOfParameterAssignments_ = null;
            return;
        }

        if(this._tRparen_ == child)
        {
            this._tRparen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tHash_ == oldChild)
        {
            setTHash((TTHash) newChild);
            return;
        }

        if(this._tLparen_ == oldChild)
        {
            setTLparen((TTLparen) newChild);
            return;
        }

        if(this._listOfParameterAssignments_ == oldChild)
        {
            setListOfParameterAssignments((PListOfParameterAssignments) newChild);
            return;
        }

        if(this._tRparen_ == oldChild)
        {
            setTRparen((TTRparen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
