/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class ARealtimeDeclaration extends PRealtimeDeclaration
{
    private TKRealtime _kRealtime_;
    private PListOfRealIdentifiers _listOfRealIdentifiers_;
    private TTSemicolon _tSemicolon_;

    public ARealtimeDeclaration()
    {
        // Constructor
    }

    public ARealtimeDeclaration(
        @SuppressWarnings("hiding") TKRealtime _kRealtime_,
        @SuppressWarnings("hiding") PListOfRealIdentifiers _listOfRealIdentifiers_,
        @SuppressWarnings("hiding") TTSemicolon _tSemicolon_)
    {
        // Constructor
        setKRealtime(_kRealtime_);

        setListOfRealIdentifiers(_listOfRealIdentifiers_);

        setTSemicolon(_tSemicolon_);

    }

    @Override
    public Object clone()
    {
        return new ARealtimeDeclaration(
            cloneNode(this._kRealtime_),
            cloneNode(this._listOfRealIdentifiers_),
            cloneNode(this._tSemicolon_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARealtimeDeclaration(this);
    }

    public TKRealtime getKRealtime()
    {
        return this._kRealtime_;
    }

    public void setKRealtime(TKRealtime node)
    {
        if(this._kRealtime_ != null)
        {
            this._kRealtime_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._kRealtime_ = node;
    }

    public PListOfRealIdentifiers getListOfRealIdentifiers()
    {
        return this._listOfRealIdentifiers_;
    }

    public void setListOfRealIdentifiers(PListOfRealIdentifiers node)
    {
        if(this._listOfRealIdentifiers_ != null)
        {
            this._listOfRealIdentifiers_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._listOfRealIdentifiers_ = node;
    }

    public TTSemicolon getTSemicolon()
    {
        return this._tSemicolon_;
    }

    public void setTSemicolon(TTSemicolon node)
    {
        if(this._tSemicolon_ != null)
        {
            this._tSemicolon_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tSemicolon_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._kRealtime_)
            + toString(this._listOfRealIdentifiers_)
            + toString(this._tSemicolon_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._kRealtime_ == child)
        {
            this._kRealtime_ = null;
            return;
        }

        if(this._listOfRealIdentifiers_ == child)
        {
            this._listOfRealIdentifiers_ = null;
            return;
        }

        if(this._tSemicolon_ == child)
        {
            this._tSemicolon_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._kRealtime_ == oldChild)
        {
            setKRealtime((TKRealtime) newChild);
            return;
        }

        if(this._listOfRealIdentifiers_ == oldChild)
        {
            setListOfRealIdentifiers((PListOfRealIdentifiers) newChild);
            return;
        }

        if(this._tSemicolon_ == oldChild)
        {
            setTSemicolon((TTSemicolon) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
