/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class ASyscallPrimary extends PPrimary
{
    private PSystemFunctionCall _systemFunctionCall_;

    public ASyscallPrimary()
    {
        // Constructor
    }

    public ASyscallPrimary(
        @SuppressWarnings("hiding") PSystemFunctionCall _systemFunctionCall_)
    {
        // Constructor
        setSystemFunctionCall(_systemFunctionCall_);

    }

    @Override
    public Object clone()
    {
        return new ASyscallPrimary(
            cloneNode(this._systemFunctionCall_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASyscallPrimary(this);
    }

    public PSystemFunctionCall getSystemFunctionCall()
    {
        return this._systemFunctionCall_;
    }

    public void setSystemFunctionCall(PSystemFunctionCall node)
    {
        if(this._systemFunctionCall_ != null)
        {
            this._systemFunctionCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._systemFunctionCall_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._systemFunctionCall_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._systemFunctionCall_ == child)
        {
            this._systemFunctionCall_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._systemFunctionCall_ == oldChild)
        {
            setSystemFunctionCall((PSystemFunctionCall) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
