/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;

@SuppressWarnings("nls")
public final class AUnaryModulePathUnaryExpression extends PModulePathUnaryExpression
{
    private PUnaryModulePathOperator _unaryModulePathOperator_;
    private PModulePathPrimary _modulePathPrimary_;

    public AUnaryModulePathUnaryExpression()
    {
        // Constructor
    }

    public AUnaryModulePathUnaryExpression(
        @SuppressWarnings("hiding") PUnaryModulePathOperator _unaryModulePathOperator_,
        @SuppressWarnings("hiding") PModulePathPrimary _modulePathPrimary_)
    {
        // Constructor
        setUnaryModulePathOperator(_unaryModulePathOperator_);

        setModulePathPrimary(_modulePathPrimary_);

    }

    @Override
    public Object clone()
    {
        return new AUnaryModulePathUnaryExpression(
            cloneNode(this._unaryModulePathOperator_),
            cloneNode(this._modulePathPrimary_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnaryModulePathUnaryExpression(this);
    }

    public PUnaryModulePathOperator getUnaryModulePathOperator()
    {
        return this._unaryModulePathOperator_;
    }

    public void setUnaryModulePathOperator(PUnaryModulePathOperator node)
    {
        if(this._unaryModulePathOperator_ != null)
        {
            this._unaryModulePathOperator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._unaryModulePathOperator_ = node;
    }

    public PModulePathPrimary getModulePathPrimary()
    {
        return this._modulePathPrimary_;
    }

    public void setModulePathPrimary(PModulePathPrimary node)
    {
        if(this._modulePathPrimary_ != null)
        {
            this._modulePathPrimary_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._modulePathPrimary_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._unaryModulePathOperator_)
            + toString(this._modulePathPrimary_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._unaryModulePathOperator_ == child)
        {
            this._unaryModulePathOperator_ = null;
            return;
        }

        if(this._modulePathPrimary_ == child)
        {
            this._modulePathPrimary_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._unaryModulePathOperator_ == oldChild)
        {
            setUnaryModulePathOperator((PUnaryModulePathOperator) newChild);
            return;
        }

        if(this._modulePathPrimary_ == oldChild)
        {
            setModulePathPrimary((PModulePathPrimary) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
