/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TDecimalNumber extends Token
{
    public TDecimalNumber(String text, int line, int pos, SourceFile sf)
    {
        super (text, line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TDecimalNumber(getText(), getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDecimalNumber(this);
    }
}
