/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKCase extends Token
{
    public TKCase(int line, int pos, SourceFile sf)
    {
        super ("case", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKCase(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKCase(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKCase text.");
    }
}
