/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKCasex extends Token
{
    public TKCasex(int line, int pos, SourceFile sf)
    {
        super ("casex", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKCasex(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKCasex(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKCasex text.");
    }
}
