/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKContinuous extends Token
{
    public TKContinuous(int line, int pos, SourceFile sf)
    {
        super ("continuous", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKContinuous(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKContinuous(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKContinuous text.");
    }
}
