/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKDeassign extends Token
{
    public TKDeassign(int line, int pos, SourceFile sf)
    {
        super ("deassign", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKDeassign(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKDeassign(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKDeassign text.");
    }
}
