/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKDiscrete extends Token
{
    public TKDiscrete(int line, int pos, SourceFile sf)
    {
        super ("discrete", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKDiscrete(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKDiscrete(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKDiscrete text.");
    }
}
