/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKDomain extends Token
{
    public TKDomain(int line, int pos, SourceFile sf)
    {
        super ("domain", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKDomain(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKDomain(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKDomain text.");
    }
}
