/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKEdge extends Token
{
    public TKEdge(int line, int pos, SourceFile sf)
    {
        super ("edge", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKEdge(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKEdge(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKEdge text.");
    }
}
