/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKEndspecify extends Token
{
    public TKEndspecify(int line, int pos, SourceFile sf)
    {
        super ("endspecify", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKEndspecify(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKEndspecify(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKEndspecify text.");
    }
}
