/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKEndgenerate extends Token
{
    public TKEndgenerate(int line, int pos, SourceFile sf)
    {
        super ("endgenerate", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKEndgenerate(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKEndgenerate(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKEndgenerate text.");
    }
}
