/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKEndtable extends Token
{
    public TKEndtable(int line, int pos, SourceFile sf)
    {
        super ("endtable", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKEndtable(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKEndtable(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKEndtable text.");
    }
}
