/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKFlow extends Token
{
    public TKFlow(int line, int pos, SourceFile sf)
    {
        super ("flow", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKFlow(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKFlow(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKFlow text.");
    }
}
