/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKForce extends Token
{
    public TKForce(int line, int pos, SourceFile sf)
    {
        super ("force", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKForce(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKForce(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKForce text.");
    }
}
