/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKHighz1 extends Token
{
    public TKHighz1(int line, int pos, SourceFile sf)
    {
        super ("highz1", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKHighz1(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKHighz1(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKHighz1 text.");
    }
}
