/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKInteger extends Token
{
    public TKInteger(int line, int pos, SourceFile sf)
    {
        super ("integer", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKInteger(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKInteger(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKInteger text.");
    }
}
