/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKInstance extends Token
{
    public TKInstance(int line, int pos, SourceFile sf)
    {
        super ("instance", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKInstance(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKInstance(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKInstance text.");
    }
}
