/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKInclude extends Token
{
    public TKInclude(int line, int pos, SourceFile sf)
    {
        super ("include", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKInclude(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKInclude(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKInclude text.");
    }
}
