/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKMacromodule extends Token
{
    public TKMacromodule(int line, int pos, SourceFile sf)
    {
        super ("macromodule", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKMacromodule(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKMacromodule(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKMacromodule text.");
    }
}
