/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKNmos extends Token
{
    public TKNmos(int line, int pos, SourceFile sf)
    {
        super ("nmos", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKNmos(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKNmos(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKNmos text.");
    }
}
