/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKNor extends Token
{
    public TKNor(int line, int pos, SourceFile sf)
    {
        super ("nor", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKNor(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKNor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKNor text.");
    }
}
