/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKPotential extends Token
{
    public TKPotential(int line, int pos, SourceFile sf)
    {
        super ("potential", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKPotential(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKPotential(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKPotential text.");
    }
}
