/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKPull0 extends Token
{
    public TKPull0(int line, int pos, SourceFile sf)
    {
        super ("pull0", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKPull0(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKPull0(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKPull0 text.");
    }
}
