/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKRepeat extends Token
{
    public TKRepeat(int line, int pos, SourceFile sf)
    {
        super ("repeat", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKRepeat(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKRepeat(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKRepeat text.");
    }
}
