/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKReal extends Token
{
    public TKReal(int line, int pos, SourceFile sf)
    {
        super ("real", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKReal(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKReal(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKReal text.");
    }
}
