/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKRtran extends Token
{
    public TKRtran(int line, int pos, SourceFile sf)
    {
        super ("rtran", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKRtran(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKRtran(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKRtran text.");
    }
}
