/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKSrecovery extends Token
{
    public TKSrecovery(int line, int pos, SourceFile sf)
    {
        super ("$recovery", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKSrecovery(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKSrecovery(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKSrecovery text.");
    }
}
