/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKSsetuphold extends Token
{
    public TKSsetuphold(int line, int pos, SourceFile sf)
    {
        super ("$setuphold", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKSsetuphold(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKSsetuphold(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKSsetuphold text.");
    }
}
