/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKTrireg extends Token
{
    public TKTrireg(int line, int pos, SourceFile sf)
    {
        super ("trireg", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKTrireg(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKTrireg(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKTrireg text.");
    }
}
