/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKUse extends Token
{
    public TKUse(int line, int pos, SourceFile sf)
    {
        super ("use", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKUse(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKUse(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKUse text.");
    }
}
