/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKUwire extends Token
{
    public TKUwire(int line, int pos, SourceFile sf)
    {
        super ("uwire", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKUwire(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKUwire(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKUwire text.");
    }
}
