/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKWhile extends Token
{
    public TKWhile(int line, int pos, SourceFile sf)
    {
        super ("while", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKWhile(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKWhile(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKWhile text.");
    }
}
