/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TKWor extends Token
{
    public TKWor(int line, int pos, SourceFile sf)
    {
        super ("wor", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TKWor(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTKWor(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TKWor text.");
    }
}
