/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TTAtStar extends Token
{
    public TTAtStar(int line, int pos, SourceFile sf)
    {
        super ("@*", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TTAtStar(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTAtStar(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTAtStar text.");
    }
}
