/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TTEg extends Token
{
    public TTEg(int line, int pos, SourceFile sf)
    {
        super ("=>", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TTEg(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTEg(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTEg text.");
    }
}
