/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TTExcl extends Token
{
    public TTExcl(int line, int pos, SourceFile sf)
    {
        super ("!", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TTExcl(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTExcl(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTExcl text.");
    }
}
