/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TTLs extends Token
{
    public TTLs(String text, int line, int pos, SourceFile sf)
    {
        super (text, line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TTLs(getText(), getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTLs(this);
    }
}
