/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.node;

import org.zamia.verilog.analysis.*;
import org.zamia.SourceFile;

@SuppressWarnings("nls")
public final class TTRs extends Token
{
    public TTRs(int line, int pos, SourceFile sf)
    {
        super (">>", line, pos, sf);
    }

    @Override
    public Object clone()
    {
      return new TTRs(getLine(), getPos(), getSource());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTRs(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTRs text.");
    }
}
