#ifndef CONFIG_FLASH_1x1
#define CONFIG_FLASH_1x1 0
#endif

#ifndef CONFIG_FLASH_1x1_PROM16
#define CONFIG_FLASH_1x1_PROM16 0
#endif

#ifndef CONFIG_FLASH_1x1_NETLIST
#define CONFIG_FLASH_1x1_NETLIST 0
#endif
