/* This file was generated by SableCC (http://www.sablecc.org/). */

package org.zamia.verilog.parser;

import org.zamia.verilog.node.*;

@SuppressWarnings("serial")
public class ParserException extends Exception
{
    Token token;

    public ParserException(@SuppressWarnings("hiding") Token token, String  message)
    {
        super(message);
        this.token = token;
    }

    public Token getToken()
    {
        return this.token;
    }
    
  	@Override
	  public String toString() {
	 	    return this.token.getSource() + ":" + token.getLine() + "," + token.getPos() + ": " + getMessage();
  	}
    
}
